# Generated by Django 3.1.6 on 2021-02-06 13:27

from django.db import migrations, models
import netguru.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('website', models.URLField(blank=True, null=True)),
                ('url_hash', models.CharField(default=netguru.utils.create_hash, max_length=32, unique=True)),
                ('url_password', models.CharField(default=netguru.utils.create_password, max_length=8)),
                ('correct_password_counter', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
