# Generated by Django 3.1.6 on 2021-02-07 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import netguru.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('website', models.URLField(blank=True, null=True)),
                ('url_hash', models.CharField(default=netguru.utils.create_hash, max_length=32, unique=True)),
                ('url_password', models.CharField(default=netguru.utils.create_password, max_length=8)),
                ('correct_password_counter', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
